version: "3.9"
services:
  fastapi-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: "8000"
      K_SERVICE: "local"
      K_CONFIGURATION: "local"
      K_REVISION: "local-docker"
      GOOGLE_APPLICATION_CREDENTIALS: "/tmp/keys/KEY.json"
      FIRESTORE_EMULATOR_HOST: "firestore:8787"
    volumes:
      - ./dev-key.json:/tmp/keys/KEY.json:ro
    depends_on:
      - firestore

  firestore:
    image: ridedott/firestore-emulator
    environment:
      PORT: "8787"
    ports:
      - "127.0.0.1:8787:8787"
    restart: unless-stopped
